/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Cab_Invoice_Generator;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Assertions;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertionsTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }

	private void assertionsTrue(String string, boolean someLibraryMethod) {
		// TODO Auto-generated method stub
		
	}
}
